[package]
name = "esp32s3-farmstick"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[[bin]]
name = "esp32s3-farmstick"
path = "./src/bin/main.rs"

[dependencies]
# ESP-HAL & RTOS ecosystem
esp-hal = { version = "~1.1.0", features = ["esp32s3", "log-04", "unstable"] }
esp-rtos = { version = "0.3.0", features = [
  "embassy",
  "esp-alloc",
  "esp32s3",
  "log-04"
] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32s3", "log-04"] }
esp-alloc = { version = "0.10.0" }

# Logging & Panics
log = "0.4.22"
esp-println = { version = "0.13.0", features = ["esp32s3", "log"] }
esp-backtrace = { version = "0.15.0", features = [
  "esp32s3",
  "panic-handler",
  "println"
] }

# Async Runtime & Embassy Ecosystem
embassy-executor = { version = "0.10.0" }
embassy-time = { version = "0.5.0" }
embassy-sync = "0.8.0"
embassy-futures = "0.1.2"
embassy-usb = { version = "0.5.0" }

# Embedded HAL & IO
embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
nb = "1.1.0"
static_cell = "2.1.1"
critical-section = "1.2.0"
heapless = "0.9.3"

# Optimization profiles for microcontrollers
[profile.dev]
# Keep size small and enable optimizations even in debug builds
opt-level = "s"

[profile.release]
opt-level = "s"
debug = 2          # Retain debug symbols for probe-rs / defmt
lto = "fat"        # Full link-time optimization
codegen-units = 1  # Best optimization at the cost of compile time
