[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"
linker = "C:\\Users\\Johannes\\.rustup\\toolchains\\esp\\xtensa-esp-elf\\bin\\xtensa-esp32s3-elf-gcc.exe"

[env]
ESP_LOG = "INFO"

[build]
rustflags = [
  "-C",
  "force-frame-pointers",
]

target = "xtensa-esp32s3-none-elf"

[unstable]
build-std = ["alloc", "core"]
